###########################################################################
#
# PDC Configuration
#
###########################################################################
pdcConfig:
  #Values -- 0x1 = PDC0, 0x2 = PDC1, 0x4=PDC2, 0x8=PDC3, 0xF=all PDCs
  # NOTE for getSpadTcrUcrCcrUsingFlag: a single PDC at the time gives better results
  pdcAcq: 0xF

  registers:
    #Configure CFG_STATUS_A
    #Values -- 0x8000 = PDC_CFG, 0x4000 = CTLCFG, 0x2000 = PDC_STATUS, 0x1000 = PDC_STATUS_ALL, 0x0007 - ALL CTL_STATUS
    #Default 0x1000 (getDsumOnCoincidence), 0x0000 (getSpadTcrU*)
    scsa: 0x1000 
    #Configure CTL_DATA_A
    #Values --
    scda: 0x00000
    #Configure PDC_DATA_A
    #Values -- 0x0100 = DSUM, 0x00F7 = ZPP
    spda: 0x0100
    #Values -- 14.4 - 18100 [ns] 
    #Default 50.0 (getDsumOnCoincidence), 150.0 (getSpadTcrU*)
    hold_time: 50.0
    #Values -- 3.4 - 58.6 [ns]
    #Default 10.0 
    recharge_time: 10.0
    #Vaues -- 1.6 - 55.3 [ns]
    #Default 2.0 (getDsumOnCoincidence), 10.0 (getSpadTcrU*)
    flag_time: 2.0

  pattern: #all
    pdc0: "0xffffffffffffffff"
    pdc1: "0xffffffffffffffff"
    pdc2: "0xffffffffffffffff"
    pdc3: "0xffffffffffffffff"
 # pattern: #mean
 #   pdc0: "0xfff4ffe7fffffffd"
 #   pdc1: "0xffffffffff77fffd" 
 #   pdc2: "0xfffefbfbff7bf7ff" 
 #   pdc3: "0x7bff7ff7fdffffff" 
  #pattern: #mean 10/30
  #  pdc0: "0xfff4fff7fffffffd"
  #  pdc1: "0xffffffffff77fffd" 
  #  pdc2: "0xfffefbffff7bf7ff" 
  #  pdc3: "0x7bff7ff7fdffffff" 
  #pattern: #threshold 700
  #  pdc0: "0xfff4fff7fffffffd"
  #  pdc1: "0xffffffffef77fffd" 
  #  pdc2: "0xfffefbfbff7bf7ff" 
  #  pdc3: "0x7bff7ff7fdffffff" 

  coincidence:
    # coincidence windows of X clock cycles
    #Values -- integer >0
    #Default 1
    window_width: 1
    # number of PDC channel for a coincidence
    #Values -- 1 to max number of PDCs
    #Default 3
    nchannels_threshold: 1
    # number of hits per PDC
    #Values -- integer >0
    #Default 1
    nhits: 1

instrumentConfig:
  hvBias: 49 #in -V, default 49

  #oscilloscope settings
  runWithLED: True
  generatorPort: 1
  pulse_frequency: 1.0 #Hz
  pulse_amplitude: 1.0 #Vpp
  pulse_offset: 0.7 #V
  pulse_dutyCycle: 0.01 #%


###########################################################################
#
# Analysis/Visualization Configuration
#
###########################################################################
dataConfig:
  name: "noLed_all" #addition to the end of the name string, for CSV data file
  savePlot: 1 #BOOL value: 0=False, 1=True
  saveYaml: 0 #BOOL value: 0=False, 1=True

  #### SCRIPT SPECIFIC - ignore for scripts not being used####
  #getSpadTcrUsingFlag AND getSpadTcrUcrCcrUsingFlag
  #defaults: 0.2, 0.1 respectively 
  measTime: 0.1 #[s]

  #getSpadTcrUsingFlag
  #options: threshold, average, percent, medianFactor, medianToMin
  screamerMethod: 'average'

  #getSpadTcrUcrCcrUsingFlag
  #after ZPP period optimization, period*nZppCycles=total duration of measurement
  nZppCycles: 5000
  zppPrd: -1 #If -1 then use OptimizegetZppOptimalPeriod method. Otherwise, use this value as the ZPP period value 

  #getDsum
  #Units of seconds. If -1, then no limit on runtime
  maxRunTime: 30
  #If -1, then no limit on number of events
  maxEvents: -1
