[project]
name = "pdcv2_modules"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "asyncssh>=2.24.0",
    "flake8>=7.3.0",
    "gevent>=26.8.0",
    "greenlet>=3.5.5",
    "h5py>=3.16.0",
    "ipython>=9.13.0",
    "matplotlib>=3.10.9",
    "numpy>=1,<2",
    "pandas>=2,<3",
    "parallel-ssh>=2.16.0.post1",
    "pyqt5>=5.15.11; sys_platform == 'linux'",
    "pytest>=9.0.3",
    "scipy>=1.17.1",
    "seaborn>=0.13.2",
    "sshconf>=0.2.7",
]
[tool.setuptools.packages.find]
include = ["pdcv2_modules"]
